### ISSUE TITLE
Project helped a lot Many Thanks

### ISSUE THREAD

**Issue by ckormanyos** [azertyfun/LibTI#3]
Hi @azertyfun I wanted to thank you for this project.

I don't know if you still support this project, but it helped me a lot in x-ing off an old TODO item from my ever-growing list of old stuff.

I learned a lot from your project. I think I got closer to solving a few problems.
  - Improved Makefile
  - Handle multiple translation units with sdcc.
  - C-runtime initialization
  - Adapted a few other ASM interfaces.
 
Anyway, if you'd like to look, then `ckormanyos/ti84-ref_app` is located [here](https://github.com/ckormanyos/ti84-ref_app).

Again, your project helped, thanks for providing this ground breaking work.

**Comment by azertyfun** [comment]
Very happy to hear that this little high school project is still helping people! Excellent job on the reference app.

It's good to see that SDCC now supports C17 as well haha, that's certainly an improvement over the partial ANSI-C support I had to contend with.

I haven't had needed to use this in several years, but I've added a link to your project in the readme.

**Comment by ckormanyos** [comment]
> Very happy to hear that this little high school project is still helping people!

Absolutely @azertyfun. You did a great job with it.

> good to see that SDCC now supports C17 as well

Yes. I first saw SDCC _come_ _around_ early this century. And I have watched it mature to this day, becoming a strong, excellent and viable option for small device development.

> added a link to your project in the readme

Thank you and thanks again
